apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
      - name: backend
        image: registry.gitlab.com/unsalsenturkk/backend:latest
        ports:
        - containerPort: 8081
